name: Build and Zip

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js 19.x
      uses: actions/setup-node@v3
      with:
        node-version: '19'

    - name: Install dependencies
      run: yarn install

    - name: Build project
      run: yarn build

    - name: Zip public directory
      run: |
        zip -r public.zip public/
      
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: public.zip
        path: public.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: public.zip
          path: ./

      - name: List directory contents
        run: |
          ls -la
          pwd

      - name: Transfer public.zip to server
        uses: appleboy/ssh-action@master
        with:
          host: bicycle.cs.washington.edu
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            scp public.zip ~/public.zip

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: bicycle.cs.washington.edu
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            rm -rf /cse/web/research/raivn/*
            mv ~/public.zip /cse/web/research/raivn/public.zip
            cd /cse/web/research/raivn
            unzip public.zip
            rm public.zip
